# Generated by Django 5.1.1 on 2024-09-13 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the event.', max_length=200)),
                ('description', models.TextField(help_text='A detailed description of the event.')),
                ('date', models.DateField(help_text='The date of the event.')),
                ('time', models.TimeField(help_text='The start time of the event.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the event was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when the event was last updated.')),
                ('attendees', models.ManyToManyField(blank=True, help_text='Users who have registered or are attending the event.', related_name='attending_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(help_text='The user or organization that is organizing the event.', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
